

EXECUTION_FAILED_FINAL_STATUSES = ['Stalled', 'Unexpected']


EXECUTION_SUCCESSFUL_FINAL_STATUSES = ['Finished']


EXECUTION_FINAL_STATUSES = EXECUTION_FAILED_FINAL_STATUSES + EXECUTION_SUCCESSFUL_FINAL_STATUSES


print(EXECUTION_FINAL_STATUSES)